// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "*.html" {
  /**
   * Raw string contents of the HTML file. Bun converts HTML imports into strings
   * that can be served directly.
   */
  const html: string;
  export = html;
}

/**
 * Helper utility type for Bun route handlers where `Request` objects are
 * augmented with a `params` property containing path parameters.
 */
export type BunRequest<P extends Record<string, string> = Record<string, string>> =
  Request & { params: P };
