[install]
# Install dependencies in a flat node_modules
# default is true unless BUNFIG_INSTALL_FLAT is false
flat = true

# Pre-install packages
pre = ["bun-plugin-tailwind"]

[install.scopes]
# Only use scoped packages from this registry
"@myorg" = { token = "$NPM_TOKEN", url = "https://registry.myorg.com/" }

[test]
# Test configuration
timeout = 5000
coverage = true
bail = 1
preload = ["./src/__tests__/setup.ts"]

# Test patterns
include = ["src/**/*.test.{ts,tsx}"]
exclude = ["node_modules/**", "dist/**", "build/**"]

# Coverage settings
coverageThreshold = 80
coverageDir = "coverage"
coverageReporter = ["text", "html", "lcov"]